name: Build Release

on:
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build Release Binary
        run: cargo build --release

      - name: Create Archive
        run: |
          cd target/release
          7z a ../../backups-of-denial-windows-x64.zip backups-of-denial.exe

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: backups-of-denial-windows-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
